# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: >
            (?x)^(
                tests/.*|
                data_dir/scylla.yaml
            )$
    -   id: check-added-large-files
    -   id: check-json

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.4.3'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        args:
        - -i
        - --max-line-length=120
        - --ignore=E226,E24,W50,W690,E402

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v1.9.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
        additional_dependencies:
            - 'requests==2.20.0'
            - 'fabric==2.4.0'
            - 'PyYAML==3.11'
            - 'boto3==1.6.5'
#            - 'apache-libcloud==2.3.0'
            - 'elasticsearch==6.0.0'
            - 'sortedcontainers==1.5.9'
            - 'jinja2==2.10'
            - 'prometheus_client==0.3.1'
            - 'pyzmq==18.0.1'
            - 'anyconfig==0.9.8'
            - 'tenacity==5.0.4'
            - 'click==7.0'
            - 'click-completion==0.5.0'
            - 'PTable==0.9.2'
            - 'backports.datetime-timestamp==1.2'
            - 'pytest==4.6.4'
